// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pour les migrations, on doit utiliser l'URL PostgreSQL standard (pas Accelerate)
    // Prisma Accelerate (prisma+postgres://) ne fonctionne pas pour les migrations
    url: env("DATABASE_POSTGRES_URL") || env("DATABASE_URL"),
  },
});
